### ISSUE TITLE
Decrease the space in Homepage

### ISSUE THREAD

**Issue by somashrirastogi** [somashrirastogi/StudyPoint#2]

**Comment by Rajeshkeshoju** [comment]
Lemme' try something!

**Comment by somashrirastogi** [comment]
> Lemme' try something!

Okay Sure

**Comment by Rajeshkeshoju** [comment]
![image](https://user-images.githubusercontent.com/39361413/137628204-b1ffc55c-305d-427f-a99c-048f30565682.png)

Is that okay?

**Comment by Rajeshkeshoju** [comment]
Do you want me make a PR then?

**Comment by Rajeshkeshoju** [comment]
Have a look at the code changes.

**Comment by somashrirastogi** [comment]
Merged

**Comment by Rajeshkeshoju** [comment]
Can you add following topics to this repo.
"Hacktoberfest", "Hactoberfest2021" and "Hacktoberfest-accepted"
